//Code by Rogier Walraven. Do not distribute.

#include "mapgenerator.h"

int main(int argc,const char **argv)
{
	if (argc<3)
	{
		exit(1);
	}

	TiXmlDocument doc(argv[1]);

	if (!doc.LoadFile())
	{
		exit(1);
	}

	bool exists;

	const char *identifier=getmap_property_string(exists,"identifier",doc);

	if (!exists)
	{
		exit(1);
	}

	FILE *outfile;
	fopen_s(&outfile,(TiXmlString(argv[2])+"\\"+identifier+"_map.h").c_str(),"w");

	if (!outfile)
	{
		exit(1);
	}

	fprintf(outfile,"//Code generated by MapCompiler.\n");

	const char *comment=getmap_property_string(exists,"comment",doc);

	if (exists)
	{
		fprintf(outfile,"//%s\n",comment);
	}

	fprintf(outfile,"\n");

	fprintf(outfile,"namespace %s_MAP\n",TiXmlString(identifier).to_uppercase().c_str());
	fprintf(outfile,"{\n");

	generate_shapes (outfile,doc);
	fprintf(outfile,"\n");
	generate_sounds (outfile,doc);
	fprintf(outfile,"\n");
	generate_motions(outfile,doc);
	fprintf(outfile,"\n");
	generate_beams  (outfile,doc);
	fprintf(outfile,"\n");
	generate_pointlights(outfile,doc);
	fprintf(outfile,"\n");
	generate_indices(outfile,doc);

	fprintf(outfile,"}\n");
	fprintf(outfile,"\n");

	generate_struct(outfile,doc);

	generate_objects(outfile,doc);

	fclose(outfile);
}
