//Code generated by MapCompiler.
//PSnakes level 3

namespace PSNAKES_LEVEL3_MAP
{
	namespace SHAPES
	{
		namespace SHAPE1
		{
			static const TRIANGLE triangle1(VECTOR(0.000000000000,1.000000000000),VECTOR(1.000000000000,0.000000000000),VECTOR(1.000000000000,1.000000000000),0.750000000000,0.250000000000,0.250000000000,8.000000000000);

			static const TRIANGLE triangles[1]={triangle1};
		}

		static const MAP_PROPERTIES::SHAPE shape1={1,0,SHAPE1::triangles,0};

		namespace SHAPE2
		{
			static const TRIANGLE triangle1(VECTOR(0.000000000000,0.000000000000),VECTOR(1.000000000000,1.000000000000),VECTOR(0.000000000000,1.000000000000),0.750000000000,0.250000000000,0.250000000000,8.000000000000);

			static const TRIANGLE triangles[1]={triangle1};
		}

		static const MAP_PROPERTIES::SHAPE shape2={1,0,SHAPE2::triangles,0};

		namespace SHAPE3
		{
			static const TRIANGLE triangle1(VECTOR(0.000000000000,0.000000000000),VECTOR(1.000000000000,0.000000000000),VECTOR(1.000000000000,1.000000000000),0.750000000000,0.250000000000,0.250000000000,8.000000000000);

			static const TRIANGLE triangles[1]={triangle1};
		}

		static const MAP_PROPERTIES::SHAPE shape3={1,0,SHAPE3::triangles,0};

		namespace SHAPE4
		{
			static const TRIANGLE triangle1(VECTOR(0.000000000000,0.000000000000),VECTOR(1.000000000000,0.000000000000),VECTOR(0.000000000000,1.000000000000),0.750000000000,0.250000000000,0.250000000000,8.000000000000);

			static const TRIANGLE triangles[1]={triangle1};
		}

		static const MAP_PROPERTIES::SHAPE shape4={1,0,SHAPE4::triangles,0};

		namespace SHAPE5
		{
			static const QUAD     quad1    (VECTOR(0.000000000000,0.000000000000),VECTOR(1.000000000000,0.000000000000),VECTOR(1.000000000000,1.000000000000),VECTOR(0.000000000000,1.000000000000),0.750000000000,0.250000000000,0.250000000000,8.000000000000);

			static const QUAD     quads    [1]={quad1};
		}

		static const MAP_PROPERTIES::SHAPE shape5={0,1,0,SHAPE5::quads};

		namespace SHAPE6
		{
			static const TRIANGLE triangle1(VECTOR(0.000000000000,0.000000000000),VECTOR(0.500000000000,1.000000000000),VECTOR(0.000000000000,1.000000000000),0.750000000000,0.250000000000,0.250000000000,8.000000000000);
			static const TRIANGLE triangle2(VECTOR(0.500000000000,1.000000000000),VECTOR(1.000000000000,0.000000000000),VECTOR(1.000000000000,1.000000000000),0.750000000000,0.250000000000,0.250000000000,8.000000000000);

			static const TRIANGLE triangles[2]={triangle1,triangle2};
		}

		static const MAP_PROPERTIES::SHAPE shape6={2,0,SHAPE6::triangles,0};
	}

	static const int numshapes=6;

	static const MAP_PROPERTIES::SHAPE shapes[6]={SHAPES::shape1,SHAPES::shape2,SHAPES::shape3,SHAPES::shape4,SHAPES::shape5,SHAPES::shape6};

	namespace AMBIENT_SOUNDS
	{
		static const MAP_PROPERTIES::AMBIENT_SOUND ambient_sound1={"Data\\Samples\\metallic_knocking.wav",VECTOR(8192.000000000000,16384.000000000000),16384.000000000000,128.000000000000,1.000000000000,0.500000000000,0.500000000000};
		static const MAP_PROPERTIES::AMBIENT_SOUND ambient_sound2={"Data\\Samples\\metallic_swing.wav",VECTOR(8192.000000000000,16384.000000000000),16384.000000000000,128.000000000000,1.000000000000,0.500000000000,0.500000000000};
		static const MAP_PROPERTIES::AMBIENT_SOUND ambient_sound3={"Data\\Samples\\metallic_drag.wav",VECTOR(8192.000000000000,16384.000000000000),16384.000000000000,128.000000000000,1.000000000000,0.500000000000,0.500000000000};
		static const MAP_PROPERTIES::AMBIENT_SOUND ambient_sound4={"Data\\Samples\\metallic_knocking.wav",VECTOR(8192.000000000000,16384.000000000000),16384.000000000000,128.000000000000,1.000000000000,0.500000000000,0.500000000000};
		static const MAP_PROPERTIES::AMBIENT_SOUND ambient_sound5={"Data\\Samples\\metallic_swing.wav",VECTOR(8192.000000000000,16384.000000000000),16384.000000000000,128.000000000000,1.000000000000,0.500000000000,0.500000000000};
		static const MAP_PROPERTIES::AMBIENT_SOUND ambient_sound6={"Data\\Samples\\metallic_drag.wav",VECTOR(8192.000000000000,16384.000000000000),16384.000000000000,128.000000000000,1.000000000000,0.500000000000,0.500000000000};
	}

	static const int numambient_sounds=6;

	static const MAP_PROPERTIES::AMBIENT_SOUND ambient_sounds[6]={AMBIENT_SOUNDS::ambient_sound1,AMBIENT_SOUNDS::ambient_sound2,AMBIENT_SOUNDS::ambient_sound3,AMBIENT_SOUNDS::ambient_sound4,AMBIENT_SOUNDS::ambient_sound5,AMBIENT_SOUNDS::ambient_sound6};

	namespace PRIMARY_LAYER
	{
		static const MAP_PROPERTIES::LINEAR_MOTION linear_motion1={VECTOR(4096.000000000000,0.000000000000),0.000000000000,128.000000000000,true,"Data\\Samples\\metallic_drag_loop.wav","Data\\Samples\\rocket_propulsion_loop.wav",1.000000000000,0.500000000000,1.000000000000,0.500000000000};
		static const MAP_PROPERTIES::LINEAR_MOTION linear_motion2={VECTOR(-4096.000000000000,0.000000000000),128.000000000000,128.000000000000,true,"Data\\Samples\\metallic_drag_loop.wav","Data\\Samples\\rocket_propulsion_loop.wav",1.000000000000,0.500000000000,1.000000000000,0.500000000000};

		static const int numlinear_motions =2;
		static const int numangular_motions=0;

		static const MAP_PROPERTIES::LINEAR_MOTION linear_motions[2]={linear_motion1,linear_motion2};
		static const MAP_PROPERTIES::ANGULAR_MOTION *angular_motions=0;
	}

	namespace SECONDARY_LAYER
	{
		static const int numlinear_motions =0;
		static const int numangular_motions=0;

		static const MAP_PROPERTIES::LINEAR_MOTION *linear_motions=0;
		static const MAP_PROPERTIES::ANGULAR_MOTION *angular_motions=0;
	}

	namespace TERTIARY_LAYER
	{
		static const int numlinear_motions =0;
		static const int numangular_motions=0;

		static const MAP_PROPERTIES::LINEAR_MOTION *linear_motions=0;
		static const MAP_PROPERTIES::ANGULAR_MOTION *angular_motions=0;
	}

	namespace PRIMARY_LAYER
	{
		static const int numbeams=0;

		static const MAP_PROPERTIES::BEAM *beams=0;
	}

	namespace SECONDARY_LAYER
	{
		static const int numbeams=0;

		static const MAP_PROPERTIES::BEAM *beams=0;
	}

	namespace TERTIARY_LAYER
	{
		static const int numbeams=0;

		static const MAP_PROPERTIES::BEAM *beams=0;
	}

	namespace PRIMARY_LAYER
	{
		static const int numpointlights=0;

		static const MAP_PROPERTIES::POINTLIGHT *pointlights=0;
	}

	namespace SECONDARY_LAYER
	{
		static const int numpointlights=0;

		static const MAP_PROPERTIES::POINTLIGHT *pointlights=0;
	}

	namespace TERTIARY_LAYER
	{
		static const int numpointlights=0;

		static const MAP_PROPERTIES::POINTLIGHT *pointlights=0;
	}

	namespace FOREGROUND_LAYER
	{
		static const int numpointlights=0;

		static const MAP_PROPERTIES::POINTLIGHT *pointlights=0;
	}

	namespace BACKGROUND_LAYER
	{
		static const int numpointlights=0;

		static const MAP_PROPERTIES::POINTLIGHT *pointlights=0;
	}

	namespace PRIMARY_LAYER
	{
		static const int texture_index[256]=
		{
			0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
			0,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,5,0,
			0,-1,-1,-1,14,14,-1,-1,-1,-1,-1,-1,14,14,-1,0,
			0,-1,-1,15,0,0,7,-1,-1,-1,-1,15,0,0,11,0,
			0,-1,-1,15,0,0,0,11,-1,-1,-1,15,0,0,11,0,
			0,-1,-1,-1,5,0,0,11,-1,-1,-1,-1,4,4,-1,0,
			0,-1,-1,-1,-1,4,4,-1,-1,-1,-1,-1,-1,-1,-1,0,
			0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,
			0,-1,-1,14,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,
			0,-1,15,0,11,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,
			0,-1,15,0,11,-1,-1,-1,-1,-1,-1,-1,-1,14,-1,0,
			0,-1,15,0,13,14,14,14,-1,-1,-1,-1,15,0,11,0,
			0,-1,15,0,0,0,0,0,11,-1,-1,-1,15,0,11,0,
			0,-1,-1,4,4,4,4,4,-1,-1,-1,-1,-1,4,-1,0,
			0,7,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,6,0,
			0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
		};

		static const int shape_index[256]=
		{
			4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,
			4,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2,4,
			4,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,4,
			4,-1,-1,-1,4,4,1,-1,-1,-1,-1,-1,4,4,-1,4,
			4,-1,-1,-1,4,4,4,-1,-1,-1,-1,-1,4,4,-1,4,
			4,-1,-1,-1,2,4,4,-1,-1,-1,-1,-1,-1,-1,-1,4,
			4,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,4,
			4,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,4,
			4,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,4,
			4,-1,-1,4,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,4,
			4,-1,-1,4,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,4,
			4,-1,-1,4,-1,-1,-1,-1,-1,-1,-1,-1,-1,4,-1,4,
			4,-1,-1,4,4,4,4,4,-1,-1,-1,-1,-1,4,-1,4,
			4,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,4,
			4,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,4,
			4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
		};
	}

	namespace SECONDARY_LAYER
	{
		static const int texture_index[256]=
		{
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
		};

		static const int shape_index[256]=
		{
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
		};
	}

	namespace TERTIARY_LAYER
	{
		static const int texture_index[256]=
		{
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
		};

		static const int shape_index[256]=
		{
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
		};
	}

	namespace FOREGROUND_LAYER
	{
		static const int texture_index[256]=
		{
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
			-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
		};
	}

	namespace BACKGROUND_LAYER
	{
		static const int texture_index[256]=
		{
			73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,
			73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,
			73,73,-1,-1,-1,-1,-1,73,73,-1,-1,-1,-1,-1,73,73,
			73,73,-1,-1,-1,-1,-1,73,73,-1,-1,-1,-1,-1,73,73,
			73,73,-1,-1,-1,-1,-1,73,73,-1,-1,-1,-1,-1,73,73,
			73,73,-1,-1,-1,-1,-1,73,73,-1,-1,-1,-1,-1,73,73,
			73,73,-1,-1,-1,-1,-1,73,73,-1,-1,-1,-1,-1,73,73,
			73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,
			73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,
			73,73,-1,-1,-1,-1,-1,73,73,-1,-1,-1,-1,-1,73,73,
			73,73,-1,-1,-1,-1,-1,73,73,-1,-1,-1,-1,-1,73,73,
			73,73,-1,-1,-1,-1,-1,73,73,-1,-1,-1,-1,-1,73,73,
			73,73,-1,-1,-1,-1,-1,73,73,-1,-1,-1,-1,-1,73,73,
			73,73,-1,-1,-1,-1,-1,73,73,-1,-1,-1,-1,-1,73,73,
			73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,
			73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73
		};
	}
}

static const MAP_PROPERTIES psnakes_level3_map_properties=
{
	0.125000000000,
	0.125000000000,
	1953.125000000000,
	16777216.000000000000,
	56.000000000000,
	0.250000000000,
	"Data\\Tilesets\\sci_fi_tiles.bmp",
	"Data\\Textures\\Skyplanes\\clouds.bmp",
	256,
	15104,
	128,
	128,
	120,
	155,
	236,
	PSNAKES_LEVEL3_MAP::numshapes,
	PSNAKES_LEVEL3_MAP::shapes,
	PSNAKES_LEVEL3_MAP::numambient_sounds,
	PSNAKES_LEVEL3_MAP::ambient_sounds,
	4.000000000000,
	4.000000000000,
	16,
	16,
	false,
	VECTOR(0.000000000000,0.000000000000),
	0.250000000000,
	1.000000000000,
	{
		PSNAKES_LEVEL3_MAP::PRIMARY_LAYER::texture_index,
		PSNAKES_LEVEL3_MAP::PRIMARY_LAYER::shape_index,
		true,
		VECTOR(0.000000000000,0.000000000000),
		0.000000000000,
		2,
		0.000000000000,
		512.000000000000,
		0,
		0,
		0,
		PSNAKES_LEVEL3_MAP::PRIMARY_LAYER::numlinear_motions,
		PSNAKES_LEVEL3_MAP::PRIMARY_LAYER::numangular_motions,
		PSNAKES_LEVEL3_MAP::PRIMARY_LAYER::linear_motions,
		PSNAKES_LEVEL3_MAP::PRIMARY_LAYER::angular_motions,
		false,
		{0,{0,0,0,0,0,0,0,0,0},{0,0,0},{0,0,0},0,0},
		PSNAKES_LEVEL3_MAP::PRIMARY_LAYER::numbeams,
		PSNAKES_LEVEL3_MAP::PRIMARY_LAYER::beams,
		PSNAKES_LEVEL3_MAP::PRIMARY_LAYER::numpointlights,
		PSNAKES_LEVEL3_MAP::PRIMARY_LAYER::pointlights
	},
	{
		PSNAKES_LEVEL3_MAP::SECONDARY_LAYER::texture_index,
		PSNAKES_LEVEL3_MAP::SECONDARY_LAYER::shape_index,
		true,
		VECTOR(0.000000000000,0.000000000000),
		0.000000000000,
		0,
		0,
		0,
		0,
		0,
		0,
		PSNAKES_LEVEL3_MAP::SECONDARY_LAYER::numlinear_motions,
		PSNAKES_LEVEL3_MAP::SECONDARY_LAYER::numangular_motions,
		PSNAKES_LEVEL3_MAP::SECONDARY_LAYER::linear_motions,
		PSNAKES_LEVEL3_MAP::SECONDARY_LAYER::angular_motions,
		false,
		{0,{0,0,0,0,0,0,0,0,0},{0,0,0},{0,0,0},0,0},
		PSNAKES_LEVEL3_MAP::SECONDARY_LAYER::numbeams,
		PSNAKES_LEVEL3_MAP::SECONDARY_LAYER::beams,
		PSNAKES_LEVEL3_MAP::SECONDARY_LAYER::numpointlights,
		PSNAKES_LEVEL3_MAP::SECONDARY_LAYER::pointlights
	},
	{
		PSNAKES_LEVEL3_MAP::TERTIARY_LAYER::texture_index,
		PSNAKES_LEVEL3_MAP::TERTIARY_LAYER::shape_index,
		true,
		VECTOR(0.000000000000,0.000000000000),
		0.000000000000,
		0,
		0,
		0,
		0,
		0,
		0,
		PSNAKES_LEVEL3_MAP::TERTIARY_LAYER::numlinear_motions,
		PSNAKES_LEVEL3_MAP::TERTIARY_LAYER::numangular_motions,
		PSNAKES_LEVEL3_MAP::TERTIARY_LAYER::linear_motions,
		PSNAKES_LEVEL3_MAP::TERTIARY_LAYER::angular_motions,
		false,
		{0,{0,0,0,0,0,0,0,0,0},{0,0,0},{0,0,0},0,0},
		PSNAKES_LEVEL3_MAP::TERTIARY_LAYER::numbeams,
		PSNAKES_LEVEL3_MAP::TERTIARY_LAYER::beams,
		PSNAKES_LEVEL3_MAP::TERTIARY_LAYER::numpointlights,
		PSNAKES_LEVEL3_MAP::TERTIARY_LAYER::pointlights
	},
	{
		PSNAKES_LEVEL3_MAP::FOREGROUND_LAYER::texture_index,
		0,
		true,
		VECTOR(0,0),
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		false,
		{0,{0,0,0,0,0,0,0,0,0},{0,0,0},{0,0,0},0,0},
		0,
		0,
		PSNAKES_LEVEL3_MAP::FOREGROUND_LAYER::numpointlights,
		PSNAKES_LEVEL3_MAP::FOREGROUND_LAYER::pointlights
	},
	{
		PSNAKES_LEVEL3_MAP::BACKGROUND_LAYER::texture_index,
		0,
		true,
		VECTOR(0,0),
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		false,
		{0,{0,0,0,0,0,0,0,0,0},{0,0,0},{0,0,0},0,0},
		0,
		0,
		PSNAKES_LEVEL3_MAP::BACKGROUND_LAYER::numpointlights,
		PSNAKES_LEVEL3_MAP::BACKGROUND_LAYER::pointlights
	}
};

namespace PSNAKES_LEVEL3_MAP
{
	namespace OBJECTS1
	{
		inline SNAKE_HEAD_OBJECT *create_snake_head_8_8(WORLD &world)
		{
			SNAKE_HEAD_OBJECT *object=new SNAKE_HEAD_OBJECT;
			object->main_init(VECTOR(4352.000000000000,4352.000000000000),0,VECTOR(0,0),0,world);
			return(object);
		}
	}
}
